// The canonical disclaimer text shown in the UI footer. Sourced from
// DISCLAIMER.md at the repo root (single source of truth — do not
// paraphrase here). Exported as both a flat string and a paragraph
// array so consumers can pick the format that fits the layout.
//
// The 4-word tagline "Not legal advice." remains as a UI banner
// (per the spec line 287 rule). The full canonical paragraph is
// the longer form below.

export const DISCLAIMER_PARAGRAPHS: readonly string[] = [
  "clausecraft is a research project, not a product. It is not legal advice.",
  "Every flag, deviation, redline, and summary produced by clausecraft is a suggestion generated by a language model. The model can be wrong. The model can be confidently wrong. The model can miss things that matter and over-flag things that don't.",
  "You are the decision-maker. clausecraft is a tool to speed up the mechanical parts of contract review (clause extraction, citation retrieval, formatting of redlines). It is not a substitute for a lawyer, a paralegal, or your own judgment.",
  "The playbook is public-source. Every clause in the baseline playbook comes from a public source (EU SCCs, IAPP, ABA, BGB, DSGVO, Tarifvertrag, etc.) with provenance attached. The system is reproducible against the playbook version, but the playbook itself is not legal advice either — it's a reference set.",
  'If we can\'t cite it, we mark it unverified. If the deviation spotter cannot find a playbook clause to compare against, it flags the deviation as "unverified" rather than asserting it. This is the central safety mechanism. Use those unverified flags as a prompt to think harder, not as a conclusion.',
  "Lawyer review required before any public deploy. This disclaimer must be reviewed by a real lawyer before clausecraft is exposed to users who might rely on its output for an actual legal decision.",
];

// Joined form, with a blank line between paragraphs. The string
// is the canonical text from DISCLAIMER.md, full stop — any
// paraphrase here will diverge from the source of truth.
export const DISCLAIMER_TEXT = DISCLAIMER_PARAGRAPHS.join("\n\n");

// Short tagline banner. The 4-word form is acceptable as a
// secondary banner per the spec; the full paragraph above is
// the primary disclaimer.
export const DISCLAIMER_TAGLINE = "Not legal advice.";
